{% set name = "allennlp" %}
{% set version = "0.8.4" %}

{% set spacy_model = "en_core_web_sm" %}
{% set spacy_model_version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ name }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 53c9c36dac6599c8b1205dcdb4640a2147e23a746c47aeb69eb5cbd4288fbcea

  # Spacy Model
  - folder: {{ spacy_model }}
    url: https://github.com/explosion/spacy-models/releases/download/{{ spacy_model }}-{{ spacy_model_version }}/{{ spacy_model }}-{{ spacy_model_version }}.tar.gz
    sha256: 4db16860a8cdef56d436038ace6abeb9181a5176bdc8c16c755a20dced51e5f1

build:
  entry_points:
    - allennlp=allennlp.run:run
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ name }} --no-deps -vv"
  skip: True  # [not linux or py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pytorch-cpu
    - jsonnet >=0.10.0
    - overrides
    - nltk
    - msgpack-python
    - spacy >=2.1.0,<2.2
    - numpy
    - tensorboardx >=1.2
    - cffi
    - awscli >=1.11.91
    - boto3
    - moto
    - flask >=1.0.2
    - flask-cors >=3.0.7
    - gevent >=1.3.6
    - requests >=2.18
    - tqdm >=4.19
    - editdistance
    - h5py
    - scikit-learn
    - scipy
    - pytz >=2017.3
    - unidecode
    - matplotlib >=2.2.3
    - pytest
    - flaky
    - responses >=0.7
    - numpydoc >=0.8.0
    - conllu ==1.3.1
    - parsimonious >=0.8.0
    - jsondiff >=0.8.0
    - ftfy
    - sqlparse >=0.2.4
    - pytorch-pretrained-bert >=0.6.0
    - word2number >=1.1

test:
  source_files:
    - {{ spacy_model }}
  commands:
    - python -m spacy link {{ spacy_model }}/{{ spacy_model }} {{ spacy_model }}
    - allennlp test-install
  imports:
    - allennlp
    - allennlp.commands
    - allennlp.common
    - allennlp.common.testing
    - allennlp.data
    - allennlp.data.dataset_readers
    - allennlp.data.dataset_readers.coreference_resolution
    - allennlp.data.dataset_readers.dataset_utils
    - allennlp.data.dataset_readers.reading_comprehension
    - allennlp.data.dataset_readers.semantic_parsing
    - allennlp.data.dataset_readers.semantic_parsing.wikitables
    - allennlp.data.fields
    - allennlp.data.iterators
    - allennlp.data.token_indexers
    - allennlp.data.tokenizers
    - allennlp.models
    - allennlp.models.coreference_resolution
    - allennlp.models.encoder_decoders
    - allennlp.models.reading_comprehension
    - allennlp.models.semantic_parsing
    - allennlp.models.semantic_parsing.atis
    - allennlp.models.semantic_parsing.nlvr
    - allennlp.models.semantic_parsing.quarel
    - allennlp.models.semantic_parsing.wikitables
    - allennlp.modules
    - allennlp.modules.attention
    - allennlp.modules.matrix_attention
    - allennlp.modules.seq2seq_encoders
    - allennlp.modules.seq2vec_encoders
    - allennlp.modules.similarity_functions
    - allennlp.modules.span_extractors
    - allennlp.modules.text_field_embedders
    - allennlp.modules.token_embedders
    - allennlp.nn
    - allennlp.nn.regularizers
    - allennlp.predictors
    - allennlp.semparse
    - allennlp.semparse.contexts
    - allennlp.semparse.executors
    - allennlp.semparse.type_declarations
    - allennlp.semparse.worlds
    - allennlp.service
    - allennlp.service.predictors
    - allennlp.state_machines
    - allennlp.state_machines.states
    - allennlp.state_machines.trainers
    - allennlp.state_machines.transition_functions
    - allennlp.tools
    - allennlp.training
    - allennlp.training.metrics
  requires:
    - ipykernel
    - jupyter
    - nltk_data

about:
  home: https://allennlp.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ name }}/LICENSE
  summary: An open-source NLP research library, built on PyTorch.
  description: |
    An Apache 2.0 NLP research library, built on PyTorch, for developing state-of-the-art 
    deep learning models on a wide variety of linguistic tasks.
  doc_url: https://allenai.github.io/allennlp-docs/
  dev_url: https://github.com/allenai/allennlp

extra:
  recipe-maintainers:
    - CurtLH
    - sodre
